name: Deploy to Inleed

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host key to known_hosts
      run: |
        ssh-keyscan -p 2020 prime5.inleed.net >> ~/.ssh/known_hosts

    - name: Sync files to Inleed
      run: |
        rsync -avz --delete -e "ssh -p 2020" --exclude '.*' . s105733@prime5.inleed.net:/home/s105733/domains/links.signedbyanna.se/public_html
